# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [415]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [416]:
print('The NumpPy version:', np.__version__)
print('The NumPy configuration:')
np.show_config()

The NumpPy version: 1.24.3
The NumPy configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    i

#### 3. Create a null vector of size 10 (★☆☆)

In [417]:
nullVector = np.zeros(10)
print(nullVector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [418]:
print(nullVector.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [419]:
###pydoc numpy.add

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [420]:
nullVector[4] = 1
print(nullVector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [421]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [422]:
vector = vector[::-1]
print(vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [423]:
vector = np.arange(9).reshape(3,3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [424]:
array = [1,2,0,0,4,0]
indices = np.nonzero(array)
print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [425]:
identityMatrix = np.eye(3,3)
print(identityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [426]:
randomArray = np.random.randint(0, 10, (3,3,3))
print(randomArray)

[[[3 0 5]
  [6 1 2]
  [3 8 3]]

 [[9 2 9]
  [6 5 0]
  [5 4 3]]

 [[4 7 1]
  [3 8 5]
  [7 4 2]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [427]:
array = np.random.randint(0, 100, (10,10))
print('The array:\n', array)
print('The minimum value:', array.min())
print('The maximum value:', array.max())

The array:
 [[95 34 47 43 58 40 16 92 46 66]
 [35 30 71 53 18 10 41 30 26 99]
 [34 95 81 32 33 54 48 50 32 50]
 [89 53 17 81 58 96 25 38 59 77]
 [80 78 52 83 22 55 35 52  8 35]
 [28 74 33 25 67 12 99  1 61 40]
 [ 3 53 60 24 44 94 11  4 34 78]
 [67 52 75 10 94 48  0 35 45 57]
 [10 99  2 69 27 50 52 59 76 38]
 [42 40 14 51 60 16 12 15 61 20]]
The minimum value: 0
The maximum value: 99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [428]:
vector = np.random.rand(30)
print('The vector:\n', vector)
print('The mean value:', vector.mean())

The vector:
 [0.92905929 0.54060893 0.69658126 0.71406737 0.05555856 0.20641244
 0.28937225 0.94515105 0.17923214 0.17653522 0.39168142 0.37504361
 0.57303207 0.28636563 0.17436915 0.57112244 0.29545022 0.11600813
 0.55593331 0.75476118 0.45062492 0.25588364 0.37039547 0.66496225
 0.06075333 0.72371351 0.38996903 0.63339166 0.81333899 0.40850938]
The mean value: 0.45326292782012645


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [429]:
array = np.ones((5,5))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [430]:
initialArray = np.arange(9).reshape(3,3)
rows, columns = initialArray.shape
print('The initial array:\n', initialArray)

array = np.zeros((rows+2, columns+2))
array[1:-1,1:-1] = initialArray
print('\nThe resulting array:\n', array)


The initial array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

The resulting array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 0.]
 [0. 3. 4. 5. 0.]
 [0. 6. 7. 8. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [431]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [432]:
array = np.diag(np.arange(1,5), k=-1)
print(array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [433]:
array = np.zeros((8,8))
array[1::2, ::2] = 1
array[::2, 1::2] = 1
print(array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [434]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [435]:
array = np.tile(np.array([[0 , 1], [1, 0]]), (4, 4))
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [436]:
array = np.random.randint(-5, 5, (5, 5))
print('The initial array:\n', array)
array = (array - np.mean(array)) / np.std(array)
print('\nThe resulting array:\n', array)

The initial array:
 [[-5  3  2  4  2]
 [ 2 -2 -3  3  1]
 [-5 -2  1 -5  1]
 [ 1 -3  0  1 -1]
 [-2 -3  0 -2 -5]]

The resulting array:
 [[-1.59480185  1.35853491  0.98936781  1.727702    0.98936781]
 [ 0.98936781 -0.48730056 -0.85646766  1.35853491  0.62020072]
 [-1.59480185 -0.48730056  0.62020072 -1.59480185  0.62020072]
 [ 0.62020072 -0.85646766  0.25103362  0.62020072 -0.11813347]
 [-0.48730056 -0.85646766  0.25103362 -0.48730056 -1.59480185]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [437]:
custom_dtype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [438]:
array1 = np.random.randint(1, 5, (5, 3))
print('The first array:\n', array1)
array2 = np.random.randint(1, 5, (3, 2))
print('\nThe second array:\n', array2)
array = np.dot(array1, array2)
print('\nThe resulting array:\n', array)

The first array:
 [[2 4 4]
 [1 3 2]
 [2 4 1]
 [4 2 2]
 [1 2 3]]

The second array:
 [[3 1]
 [3 4]
 [3 4]]

The resulting array:
 [[30 34]
 [18 21]
 [21 22]
 [24 20]
 [18 21]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [439]:
array = np.random.randint(0, 10, 15)
print('The initial array:', array)
array[(3 < array) & (array < 8)] *= -1
print('\nThe resulting array:', array)

The initial array: [1 2 7 6 2 5 0 7 9 7 4 6 7 6 3]

The resulting array: [ 1  2 -7 -6  2 -5  0 -7  9 -7 -4 -6 -7 -6  3]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [445]:
print(np.sum(range(5), -1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(5)
print('The array:\n', Z)
print('\nZ**Z\n', (Z**Z))
print('\n2 << Z >> 2\n', (2 << Z >> 2))
print('\nZ <- Z\n', (Z <- Z))
print('\n1j * Z\n', (1j*Z))
print('\nZ/1/1\n', (Z/1/1))
#print('\nZ<Z>Z\n', (Z<Z>Z))

The array:
 [0 1 2 3 4]

Z**Z
 [  1   1   4  27 256]

2 << Z >> 2
 [0 1 2 4 8]

Z <- Z
 [False False False False False]

1j * Z
 [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]

Z/1/1
 [0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print('np.array(0) / np.array(0) =', np.array(0) / np.array(0))

print('\nnp.array(0) // np.array(0) =', np.array(0) // np.array(0))

print('\nnp.array([np.nan]).astype(int).astype(float) =', np.array([np.nan]).astype(int).astype(float))

np.array(0) / np.array(0) = nan

np.array(0) // np.array(0) = 0

np.array([np.nan]).astype(int).astype(float) = [-2.14748365e+09]


C:\Users\user\AppData\Local\Temp\ipykernel_8932\2212509283.py:1: RuntimeWarning: invalid value encountered in divide
  print('np.array(0) / np.array(0) =', np.array(0) / np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_8932\2212509283.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print('\nnp.array(0) // np.array(0) =', np.array(0) // np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_8932\2212509283.py:5: RuntimeWarning: invalid value encountered in cast
  print('\nnp.array([np.nan]).astype(int).astype(float) =', np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
array = np.arange(-3.2, 4, 0.75)
print('The initial array:\n', array)
array = np.where(array > 0, np.ceil(array), np.floor(array))
print('\nThe resulting array:\n', array)

The initial array:
 [-3.2  -2.45 -1.7  -0.95 -0.2   0.55  1.3   2.05  2.8   3.55]

The resulting array:
 [-4. -3. -2. -1. -1.  1.  2.  3.  3.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
array1 = np.random.randint(-5, 5, 10)
array2 = np.random.randint(-5, 5, 10)
print('The first array:\n', array1)
print('\nThe second array:\n', array2)
print('\nThe common values:\n', np.intersect1d(array1, array2))

The first array:
 [ 3  1 -4  4  1  3  1 -1  0 -1]

The second array:
 [-4 -3  1 -5  2 -1 -3  3 -4 -1]

The common values:
 [-4 -1  1  3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
print(np.geterr(), '\n')
settings = np.seterr(all='ignore') 
print(np.geterr(), '\n')
print(np.array(0) / np.array(0))
np.seterr(**settings)
print(np.geterr())
print(np.array(0) / np.array(0))

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'} 

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'} 

nan
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
nan


C:\Users\user\AppData\Local\Temp\ipykernel_8932\3434036659.py:7: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [446]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\user\AppData\Local\Temp\ipykernel_8932\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1)
tomorrow = today + np.timedelta64(1)

print('Yesterday:', yesterday)
print('Today:', today)
print('Tomorrow:', tomorrow)

Yesterday: 2023-10-24
Today: 2023-10-25
Tomorrow: 2023-10-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
july = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.array([1, 3, 5], dtype=float)
B = np.array([2, 4, 6], dtype=float)

print('A:', A)
print('\nB:', B)

np.add(A, B, out=B)
print('\nadd:', B)
np.negative(A, out=A)
print('\nnegative:', A)
np.divide(A, 2, out=A)
print('\ndivide:', A)
np.multiply(B, A, out=A)
print('\nmultiply:', A)

A: [1. 3. 5.]

B: [2. 4. 6.]

add: [ 3.  7. 11.]

negative: [-1. -3. -5.]

divide: [-0.5 -1.5 -2.5]

multiply: [ -1.5 -10.5 -27.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
array = np.random.rand(5)*10
print('The initial array:\n', array)
print('\nThe first method:', array // 1)
print('\nThe second method:', np.ceil(array))
print('\nThe third method:', np.floor(array))
print('\nThe fourth method:', np.trunc(array))

The initial array:
 [6.40984014 0.58944717 2.03361379 5.96809852 8.47991443]

The first method: [6. 0. 2. 5. 8.]

The second method: [7. 1. 3. 6. 9.]

The third method: [6. 0. 2. 5. 8.]

The fourth method: [6. 0. 2. 5. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [448]:
array = np.tile(np.array(np.arange(5)), (5, 1))
print(array)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator():
    for i in range(10):
        yield i

array = np.fromiter(generator(), dtype=int)

print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [453]:
#array = np.random.rand(10)
#array = np.arange(0, 1, 0.09)[1:11]
array = np.linspace(0, 1, 11, endpoint=False)[1:]
print(array)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
array = np.random.random(10)*10
array.sort()
print(array)

[1.02096276 1.38430679 1.65529751 4.17383356 4.59162575 4.72878831
 5.34914424 6.18259361 7.56826003 8.67398541]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [455]:
array = np.random.randint(0, 10, 5)
print('The array:', array)
print(np.add.reduce(array))

The array: [5 7 2 9 2]
25


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [493]:
A = np.random.randint(0, 3, 3)
B = np.random.randint(0, 3, 3)
print('A:', A)
print('B:', B)
print(np.array_equal(A,B))

A: [1 2 2]
B: [1 2 2]
True


#### 43. Make an array immutable (read-only) (★★☆)

In [495]:
array = np.arange(5)
array.flags.writeable = False
print('The initial array:', array)
#array[2] = 9

The initial array: [0 1 2 3 4]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [517]:
array = np.random.random((10, 2))

x, y = array[:, 0], array[:, 1]

radius = np.sqrt(x**2 + y**2)
angle = np.arctan2(y, x)

print('The cartesian coordinates:\n', array)
print('\nThe polar coordinates:')
print('The radius:\n', radius)
print('The angle:\n', angle)

The cartesian coordinates:
 [[0.64799852 0.63646189]
 [0.02677825 0.70003133]
 [0.95210519 0.19733364]
 [0.49258635 0.9293064 ]
 [0.21877145 0.99699757]
 [0.22429707 0.50841382]
 [0.65370597 0.18646938]
 [0.19415511 0.15894454]
 [0.39194205 0.32834036]
 [0.42394349 0.72348075]]

The polar coordinates:
The radius:
 [0.9082873  0.70054331 0.97233988 1.051785   1.02071794 0.55569217
 0.67978108 0.25091747 0.51129831 0.83854187]
The angle:
 [0.77641672 1.53256204 0.2043668  1.08339242 1.35478951 1.1553094
 0.27787002 0.68600823 0.69732554 1.04075124]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [520]:
array = np.random.randint(0, 10, 10)
print('The initial array:\n', array)
array[array.argmax()] = 0
print('\nThe resulting array:\n', array)

The initial array:
 [3 0 5 9 0 3 1 7 6 5]

The resulting array:
 [3 0 5 0 0 3 1 7 6 5]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [573]:
x, y = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

array = np.ones((5*5), dtype=[('x', float), ('y', float)])

array['x'] = x.flatten()
array['y'] = y.flatten()

print("The structured array:")
print(array)

The structured array:
[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(1, 8)
Y = np.arange(5, 12)

print('X:', X)
print('\nY:', Y)

array = 1 / np.subtract.outer(X, Y)
print('\nThe Cauchy matrix:\n', array)

X: [1 2 3 4 5 6 7]

Y: [ 5  6  7  8  9 10 11]

The Cauchy matrix:
 [[-0.25       -0.2        -0.16666667 -0.14285714 -0.125      -0.11111111
  -0.1       ]
 [-0.33333333 -0.25       -0.2        -0.16666667 -0.14285714 -0.125
  -0.11111111]
 [-0.5        -0.33333333 -0.25       -0.2        -0.16666667 -0.14285714
  -0.125     ]
 [-1.         -0.5        -0.33333333 -0.25       -0.2        -0.16666667
  -0.14285714]
 [        inf -1.         -0.5        -0.33333333 -0.25       -0.2
  -0.16666667]
 [ 1.                 inf -1.         -0.5        -0.33333333 -0.25
  -0.2       ]
 [ 0.5         1.                 inf -1.         -0.5        -0.33333333
  -0.25      ]]


C:\Users\user\AppData\Local\Temp\ipykernel_8932\4057165680.py:7: RuntimeWarning: divide by zero encountered in divide
  array = 1 / np.subtract.outer(X, Y)


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
itypes = [np.int8, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64]
ftypes = [np.float32, np.float64]

for type in itypes:
    info = np.iinfo(type)
    print(f'The minimum representable value for {type.__name__}:', info.min)
    print(f'The maximum representable value for {type.__name__}:', info.max)
    print()

for type in ftypes:
    info = np.finfo(type)
    print(f'The minimum representable value for {type.__name__}:', info.min)
    print(f'The maximum representable value for {type.__name__}:', info.max)
    print()

The minimum representable value for int8: -128
The maximum representable value for int8: 127

The minimum representable value for int32: -2147483648
The maximum representable value for int32: 2147483647

The minimum representable value for int64: -9223372036854775808
The maximum representable value for int64: 9223372036854775807

The minimum representable value for uint8: 0
The maximum representable value for uint8: 255

The minimum representable value for uint16: 0
The maximum representable value for uint16: 65535

The minimum representable value for uint32: 0
The maximum representable value for uint32: 4294967295

The minimum representable value for uint64: 0
The maximum representable value for uint64: 18446744073709551615

The minimum representable value for float32: -3.4028235e+38
The maximum representable value for float32: 3.4028235e+38

The minimum representable value for float64: -1.7976931348623157e+308
The maximum representable value for float64: 1.7976931348623157e+308



#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float("inf"))
array = np.zeros((100,100))
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [523]:
array = np.arange(1, 20, 3)
scalar = 12

print('The array:', array)
print('\nThe scalar:', scalar)

element = np.abs(array - scalar).argmin()
print('\nThe closest value:', array[element])

The array: [ 1  4  7 10 13 16 19]

The scalar: 12

The closest value: 13


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
dtype = np.dtype([
                ('position', [('x', int), ('y', int)]), 
                ('color', [('r', int), ('g', int), ('b', int)])
                ])

array = np.ones(3, dtype=dtype)
print(array)

[((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [529]:
array = np.random.randint(1, 5, (4, 2))
print('The array:\n', array)

distances = np.linalg.norm(array[:, np.newaxis] - array, axis=2)
print('\nThe point by point distances:\n', distances)

The array:
 [[4 2]
 [1 3]
 [1 2]
 [1 3]]

The point by point distances:
 [[0.         3.16227766 3.         3.16227766]
 [3.16227766 0.         1.         0.        ]
 [3.         1.         0.         1.        ]
 [3.16227766 0.         1.         0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
array = np.random.random(10).astype(np.float32)*10
print(f'The {array.dtype} array:\n', array)
array = array.astype(np.int32)
print(f'\nThe {array.dtype} array:\n', array)

The float32 array:
 [3.2979841  6.4600616  8.918187   4.963874   3.0606759  1.2971591
 0.05631098 3.0632355  6.387721   6.8278623 ]

The int32 array:
 [3 6 8 4 3 1 0 3 6 6]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
file = '54.txt'

array = np.genfromtxt(file, delimiter=",", dtype=np.int32, filling_values=0)
print(array)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
array = np.arange(2, 6).reshape(2,2)

for index, value in np.ndenumerate(array):
    print(f'Index: {index}\tValue: {value}')

Index: (0, 0)	Value: 2
Index: (0, 1)	Value: 3
Index: (1, 0)	Value: 4
Index: (1, 1)	Value: 5


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [534]:
X, Y = np.meshgrid(np.linspace(-1,1,3), np.linspace(-1,1,3))
print('X:\n', X)
print('\nY:\n', Y)

distances = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
gaussian_function = np.exp(-( (distances-mu)**2 / ( 2.0 * sigma**2 ) ) )

print('\nThe result:\n',gaussian_function)

X:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]

Y:
 [[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]

The result:
 [[0.36787944 0.60653066 0.36787944]
 [0.60653066 1.         0.60653066]
 [0.36787944 0.60653066 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
array = np.zeros((5, 5))
print('The initial array:\n', array)
indices = np.random.choice(range(5*5), 10, replace=False)
print('\nThe indices:\n', indices)
values = np.random.randint(1, 10, 10)
print('\nThe values:\n', values)
np.put(array, indices, values)
print('\nThe resulting array:\n', array)

The initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

The indices:
 [ 2 19 18  4  9 22  8 15  3 14]

The values:
 [4 6 6 8 4 7 6 1 5 8]

The resulting array:
 [[0. 0. 4. 5. 8.]
 [0. 0. 0. 6. 4.]
 [0. 0. 0. 0. 8.]
 [1. 0. 0. 6. 6.]
 [0. 0. 7. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
array = np.random.randint(0, 10, (3, 3))
print('The initial array:\n', array)
meanValues = np.mean(array, axis=1, keepdims=True)
print('\nThe mean value:\n', meanValues)
array = array - meanValues
print('\nThe resulting array:\n', array)

The initial array:
 [[0 5 9]
 [2 8 9]
 [7 6 7]]

The mean value:
 [[4.66666667]
 [6.33333333]
 [6.66666667]]

The resulting array:
 [[-4.66666667  0.33333333  4.33333333]
 [-4.33333333  1.66666667  2.66666667]
 [ 0.33333333 -0.66666667  0.33333333]]


#### 59. How to sort an array by the nth column? (★★☆)

In [536]:
array = np.random.randint(1, 10, (3, 3))
print('The initial array:\n', array)
n = 0
array = array[array[:, n].argsort()]
print('\nThe resulting array:\n', array)

The initial array:
 [[7 4 8]
 [2 6 6]
 [9 9 5]]

The resulting array:
 [[2 6 6]
 [7 4 8]
 [9 9 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [542]:
array = np.random.randint(0,3,(3,3))
print('The array:\n', array)
nullColumns = (~array.any(axis=0)).any()
print('\nThe array has null columns:', nullColumns)

The array:
 [[0 1 0]
 [1 1 0]
 [0 2 0]]

The array has null columns: True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [548]:
array = np.random.randint(0, 10, 5)
print('The array:', array)
value = 3.7
print('The given value:', value)
print('The nearest value:', array[(np.abs(array - value)).argmin()])

The array: [6 6 4 0 2]
The given value: 3.7
The nearest value: 4


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [563]:
array1 = np.random.randint(0, 10, (1, 3))
array2 = np.random.randint(0, 10, (3, 1))
print('The first array:\n', array1)
print('\nThe second array:\n', array2)

iterator = np.nditer([array1, array2, None])

for a, b, sum in iterator:
    sum[...] = a + b

sum = iterator.operands[2]

print('\nThe sum:\n', sum)

The first array:
 [[5 2 4]]

The second array:
 [[5]
 [7]
 [9]]

The sum:
 [[10  7  9]
 [12  9 11]
 [14 11 13]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class namedArray(np.ndarray):
    def __new__(cls, arr, name='Unnamed'):
        obj = np.asarray(arr).view(cls)
        obj.name = name
        return obj

array = namedArray(np.arange(5), name='array name')
print('The array name:', array.name, '\n', array)

The array name: array name 
 [0 1 2 3 4]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
vector = np.random.randint(0, 10, 10)
print('The initial vector:', vector)

indices = np.random.choice(len(vector), 5)
print('The indices:', indices)

unique, counts = np.unique(indices, return_counts=1)

vector[unique] += counts

print("\nThe resulting vector:", vector)

The initial vector: [8 3 7 4 1 7 9 5 5 6]
The indices: [1 4 8 4 4]

The resulting vector: [8 4 7 4 4 7 9 5 6 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = np.random.randint(0, 10, 10)
print('X:', X)

I = np.random.choice(len(X), len(X))
print('I:', I)

F = np.bincount(I,X)
print('F:', F)

X: [4 1 4 1 7 1 8 3 9 1]
I: [9 6 0 9 2 2 6 8 6 6]
F: [ 4.  0.  8.  0.  0.  0. 19.  0.  3.  5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [567]:
image = np.random.randint(0, 4, size=(2, 10, 3), dtype=np.ubyte)
print('Image:\n', image)
unique_colors = np.unique(image.reshape(-1, 3), axis=0)
print('\nThe number of unique colors:', len(unique_colors))


Image:
 [[[2 0 1]
  [0 2 2]
  [3 2 1]
  [2 3 1]
  [1 0 3]
  [1 0 1]
  [0 2 1]
  [0 1 3]
  [0 3 2]
  [2 1 0]]

 [[1 2 3]
  [1 2 2]
  [2 0 2]
  [1 0 2]
  [1 3 0]
  [2 1 1]
  [0 0 2]
  [2 0 2]
  [3 2 3]
  [2 2 3]]]

The number of unique colors: 19


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [569]:
array = np.random.randint(0, 5, (2, 2, 2, 2))
print('The 4D array:\n', array)
print('\nThe sum:\n', np.sum(array, axis=(2, 3)))

The 4D array:
 [[[[3 4]
   [3 1]]

  [[3 1]
   [2 0]]]


 [[[2 3]
   [3 4]]

  [[2 0]
   [3 3]]]]

The sum:
 [[11  6]
 [12  8]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.randint(0, 10, 9)
S = np.array([0, 0, 1, 1, 2, 2, 3, 3, 3]) 

print('The 1D vector D:', D)

means = [D[S == i].mean() for i in np.unique(S)]
print("The means of subsets:", means)

The 1D vector D: [8 8 4 1 1 9 8 2 6]
The means of subsets: [8.0, 2.5, 5.0, 5.333333333333333]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
array1 = np.random.randint(0, 5, (3,3))
array2 = np.random.randint(0, 5, (3,3))

print('The first array:\n', array1)
print('\nThe second array:\n', array2)

result = np.diag(np.dot(array1, array2))

print('\nThe dot product:\n', np.dot(array1, array2))
print('\nThe diagonal of a dot product:\n', result)

The first array:
 [[2 2 2]
 [3 0 0]
 [2 1 2]]

The second array:
 [[3 1 0]
 [0 2 0]
 [3 1 0]]

The dot product:
 [[12  8  0]
 [ 9  3  0]
 [12  6  0]]

The diagonal of a dot product:
 [12  3  0]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
vector = np.array([1, 2, 3, 4, 5])

result = np.zeros(len(vector)*3+2)
result[::4] = vector

print(result)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
array1 = np.tile(np.array(np.arange(1, 4)), (5, 5, 1))
print('The 3D array:\n', array1[0])

array2 = np.tile(np.array(np.arange(5)), (5, 1))

print('\nThe 2D array:\n', array2)
print('\nThe result:\n', array1 * array2[:,:,np.newaxis])



The 3D array:
 [[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]

The 2D array:
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

The result:
 [[[ 0  0  0]
  [ 1  2  3]
  [ 2  4  6]
  [ 3  6  9]
  [ 4  8 12]]

 [[ 0  0  0]
  [ 1  2  3]
  [ 2  4  6]
  [ 3  6  9]
  [ 4  8 12]]

 [[ 0  0  0]
  [ 1  2  3]
  [ 2  4  6]
  [ 3  6  9]
  [ 4  8 12]]

 [[ 0  0  0]
  [ 1  2  3]
  [ 2  4  6]
  [ 3  6  9]
  [ 4  8 12]]

 [[ 0  0  0]
  [ 1  2  3]
  [ 2  4  6]
  [ 3  6  9]
  [ 4  8 12]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
array = np.arange(9).reshape(3, 3)
print('The initial array:\n', array)
array[[0, 2]] = array[[2, 0]]
print('\nThe resulting array:\n', array)

The initial array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

The resulting array:
 [[6 7 8]
 [3 4 5]
 [0 1 2]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
lines = np.random.randint(0,10,(10,3))
lines = np.roll(lines.repeat(2,axis=1),-1,axis=1).reshape(len(lines)*3, 2)

lines = np.sort(lines,axis=1)
print('The lines:\n', lines)
print('\nThe number of lines:', len(lines))

result = np.unique(lines, axis=0)
print('\nThe unique lines:\n', result)
print('\nThe number of lines:', len(result))

The lines:
 [[3 8]
 [1 8]
 [1 3]
 [5 6]
 [5 6]
 [5 5]
 [4 4]
 [3 4]
 [3 4]
 [2 3]
 [2 9]
 [3 9]
 [3 7]
 [3 6]
 [6 7]
 [1 8]
 [4 8]
 [1 4]
 [1 1]
 [1 8]
 [1 8]
 [0 4]
 [0 4]
 [0 0]
 [1 8]
 [1 1]
 [1 8]
 [2 8]
 [6 8]
 [2 6]]

The number of lines: 30

The unique lines:
 [[0 0]
 [0 4]
 [1 1]
 [1 3]
 [1 4]
 [1 8]
 [2 3]
 [2 6]
 [2 8]
 [2 9]
 [3 4]
 [3 6]
 [3 7]
 [3 8]
 [3 9]
 [4 4]
 [4 8]
 [5 5]
 [5 6]
 [6 7]
 [6 8]]

The number of lines: 21


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([0, 2, 1, 2, 5, 3, 0])
print('C:', C)
A = np.repeat(np.arange(len(C)), C)
print('A:', A)
#print(np.bincount(A) == C)

C: [2 1 2 1 0 1]
A: [0 0 1 2 2 3 5]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view

array = np.arange(10)
print('The array:', array)
window = 2

#averages = np.convolve(array, np.ones(window) / window, mode='valid')

averages = sliding_window_view(array, window).mean(axis=-1)

print('The averages:', averages)

The array: [0 1 2 3 4 5 6 7 8 9]
The averages: [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
Z = np.arange(10)
print('The 1D array:', Z)

""" result = np.ones((len(Z) - 2, 3), dtype=Z.dtype)

for i in range(len(result)):
    result[i] = Z[i:i + 3] """

result = sliding_window_view(Z, 3)
print('The 2D array:\n', result)

The 1D array: [0 1 2 3 4 5 6 7 8 9]
The 2D array:
 [[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
boolean_array = np.random.choice((True, False), 10)
print('The boolean array:', boolean_array)

boolean_array = np.logical_not(boolean_array)
print('The negated boolean array:', boolean_array)

float_array = np.random.randint(-10, 10, 10)
print('The float array:', float_array)

float_array = np.negative(float_array)
print('The float array with changed sign:', float_array)

The boolean array: [False False  True  True False False  True  True  True False]
The negated boolean array: [ True  True False False  True  True False False False  True]
The float array: [ -4   8 -10   3   0   8  -7  -6  -6  -9]
The float array with changed sign: [ 4 -8 10 -3  0 -8  7  6  6  9]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def computeDistance(P0, P1, p):
    distances = list()

    for i in range(len(P0)):
        distance = np.abs(np.cross(P1[i] - P0[i], p - P0[i])) / np.linalg.norm(P1[i] - P0[i])
        distances.append(distance)
    
    return distances

P0 = np.random.randint(0, 9, (3, 2))
print('P0:\n', P0)
P1 = np.random.randint(0, 9, (3, 2))
print('\nP1:\n', P1)
p = np.array([2, 2])

distances = computeDistance(P0, P1, p)
print(f'\nThe distance from {p} to line:', distances)

P0:
 [[5 2]
 [2 0]
 [4 3]]

P1:
 [[2 4]
 [5 1]
 [5 8]]

The distance from [2 2] to line: [1.6641005886756874, 1.8973665961010275, 1.7650452162436565]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
p = np.random.randint(0, 9, (2, 2))
print('p:\n', p)

distances = np.array([computeDistance(P0, P1, p[i]) for i in range(len(p))])
print('\nThe distance from p to line:\n', distances)

p:
 [[3 6]
 [6 8]]

The distance from p to line:
 [[2.21880078 5.37587202 1.56892908]
 [5.54700196 6.32455532 0.98058068]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
array = np.random.randint(0, 10, (10, 10))
print('The array:\n', array)

shape = (7, 7)
position = (0, 0)


result = np.zeros(shape, dtype=array.dtype)

shape0 = shape[0] // 2
shape1 = shape[1] // 2

start1 = int(max(shape0 - position[0], 0))
start2 = int(max(shape1 - position[1], 0))
end1 = int(min(len(array) - position[0] + shape0, shape[0]))
end2 = int(min(len(array) - position[1] + shape1, shape[1]))

startArray1 = int(max(position[0] - shape0, 0))
startArray2 = int(max(position[1] - shape1, 0))
endArray1 = int(min(position[0] + shape0 + 1, len(array)))
endArray2 = int(min(position[1] + shape1 + 1, len(array)))

result[start1 : end1, start2 : end2] = array[startArray1 : endArray1, startArray2 : endArray2]

print('\nThe result:\n', result)

The array:
 [[7 2 7 4 2 4 5 4 3 6]
 [8 4 6 7 9 4 7 7 8 1]
 [7 3 8 7 3 6 6 8 3 8]
 [4 6 0 4 1 7 3 7 6 6]
 [6 6 5 8 4 5 1 0 5 6]
 [9 9 0 1 0 5 4 9 2 2]
 [3 7 2 3 7 7 2 0 4 4]
 [4 6 0 0 0 4 2 8 9 9]
 [0 9 8 2 4 7 8 6 2 6]
 [3 4 1 0 7 3 4 0 8 1]]

The result:
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 7 2 7 4]
 [0 0 0 8 4 6 7]
 [0 0 0 7 3 8 7]
 [0 0 0 4 6 0 4]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(0, 15)
print('The 1D array:', Z)

R = sliding_window_view(Z, 4)

print('The 2D array:\n', R)

The 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
The 2D array:
 [[ 0  1  2  3]
 [ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [ ]:
from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)



[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
array = np.array([[1, 3, 1, 2, 1], 
                  [2, 2, 1, 3, 1],
                  [3, 1, 4, -1, 0],
                  [4, 4, 2, 6, 2]])
print('The array:\n', array)

rank = np.linalg.matrix_rank(array)
print('\nThe matrix rank:', rank)

The array:
 [[ 1  3  1  2  1]
 [ 2  2  1  3  1]
 [ 3  1  4 -1  0]
 [ 4  4  2  6  2]]

The matrix rank: 3


#### 83. How to find the most frequent value in an array?

In [ ]:
array = np.random.randint(0, 4, 10)
print('The array:', array)
value = np.bincount(array).argmax()
print('The frequent value:', value)

The array: [3 0 3 3 2 2 2 1 1 0]
The frequent value: 2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
array = np.random.randint(0, 10, (10, 10))
print('The array:\n', array)
result = sliding_window_view(array, (3, 3))
print('\nThe result:\n', result)

The array:
 [[1 9 0 5 6 6 4 0 8 6]
 [4 3 2 2 9 4 4 0 0 7]
 [1 2 8 9 8 2 6 5 4 9]
 [2 4 3 6 8 5 7 3 2 6]
 [4 5 7 7 7 4 6 4 2 0]
 [9 0 2 5 1 5 2 3 7 3]
 [4 5 1 9 4 9 6 2 0 9]
 [7 3 7 3 4 9 3 2 8 3]
 [3 7 7 4 0 6 2 6 3 9]
 [1 5 7 5 9 1 0 7 5 2]]

The result:
 [[[[1 9 0]
   [4 3 2]
   [1 2 8]]

  [[9 0 5]
   [3 2 2]
   [2 8 9]]

  [[0 5 6]
   [2 2 9]
   [8 9 8]]

  [[5 6 6]
   [2 9 4]
   [9 8 2]]

  [[6 6 4]
   [9 4 4]
   [8 2 6]]

  [[6 4 0]
   [4 4 0]
   [2 6 5]]

  [[4 0 8]
   [4 0 0]
   [6 5 4]]

  [[0 8 6]
   [0 0 7]
   [5 4 9]]]


 [[[4 3 2]
   [1 2 8]
   [2 4 3]]

  [[3 2 2]
   [2 8 9]
   [4 3 6]]

  [[2 2 9]
   [8 9 8]
   [3 6 8]]

  [[2 9 4]
   [9 8 2]
   [6 8 5]]

  [[9 4 4]
   [8 2 6]
   [8 5 7]]

  [[4 4 0]
   [2 6 5]
   [5 7 3]]

  [[4 0 0]
   [6 5 4]
   [7 3 2]]

  [[0 0 7]
   [5 4 9]
   [3 2 6]]]


 [[[1 2 8]
   [2 4 3]
   [4 5 7]]

  [[2 8 9]
   [4 3 6]
   [5 7 7]]

  [[8 9 8]
   [3 6 8]
   [7 7 7]]

  [[9 8 2]
   [6 8 5]
   [7 7 4]]

  [[8 2 6]
   [8 5 7]
   [7 4 6]]

  [[

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class subclass(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __getitem__(self, index):
        i, j = index
        if i < j:
            return self.data[j, i]
        else:
            return self.data[i, j]

array = np.array([[1, 2, 1],
                [2, 4, 4],
                [5, 5, 6]])

result = subclass(array)

print(result)

[[1 2 5]
 [2 4 5]
 [5 5 6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 3, 4
matrices = np.ones((p,n,n))
matrices[0] *= 2
matrices[0, 1] -= 1
print('The matrices:\n', matrices)
vectors = np.ones((p,n,1))
vectors[0] *= 2
#vectors[0, 0] -= 1
print('\nThe vectors:\n', vectors)
result = np.tensordot(matrices, vectors, axes=[[0, 2], [0, 1]])
print('The result:\n', result)


The matrices:
 [[[2. 2. 2. 2.]
  [1. 1. 1. 1.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

The vectors:
 [[[2.]
  [2.]
  [2.]
  [2.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]]
The result:
 [[24.]
 [16.]
 [24.]
 [24.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
array = np.tile(np.array(np.arange(1, 9)), (16, 2))
print('The array:\n', array)
array = sliding_window_view(array, (4, 4))[::4, ::4]
result = array.sum(axis=(-2, -1))

""" result = list()
for i in range(4):
    for j in range(4):
        result.append(np.sum(arr[i, j]))
result = np.array(result).reshape(4, 4) """

print('\nThe block-sum\n', result)

The array:
 [[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]]

The block-sum
 [[ 40 104  40 104]
 [ 40 104  40 104]
 [ 40 104  40 104]
 [ 40 104  40 104]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def output_2D_array(matrix):
    for row in matrix:
        for item in row:
            print(f"{round(item, 2)}\t", end='')
        print()
    print()

def step(array):
    number = sliding_window_view(array, (3, 3))
    number = number.sum(axis=(-2, -1)) - number[:, 1, 1]

    print(number)

    new = (number==3) & (array[1:-1,1:-1]==0)
    save = ((number==2) | (number==3)) & (array[1:-1,1:-1]==1)
    array[:, :] = 0
    array[1:-1,1:-1][new | save] = 1
    return array

maxSize = 5

array = np.random.randint(0,2,(maxSize, maxSize))
output_2D_array(array)
continueGame = True
l = 0
while continueGame:
    array = step(array)
    output_2D_array(array)
    continueGame = not np.array_equal(array, np.zeros((maxSize, maxSize)))
    l += 1
    if l == 10:
        break

0	1	1	0	0	
1	1	0	0	1	
0	1	0	0	1	
0	0	1	1	0	
0	0	0	1	0	

[[4 4 3]
 [3 4 4]
 [2 3 3]]
0	0	0	0	0	
0	0	0	1	0	
0	1	0	0	0	
0	0	1	1	0	
0	0	0	0	0	

[[1 2 0]
 [1 4 3]
 [2 2 1]]
0	0	0	0	0	
0	0	0	0	0	
0	0	0	1	0	
0	0	1	0	0	
0	0	0	0	0	

[[0 1 1]
 [1 2 1]
 [1 1 2]]
0	0	0	0	0	
0	0	0	0	0	
0	0	0	0	0	
0	0	0	0	0	
0	0	0	0	0	



#### 89. How to get the n largest values of an array (★★★)

In [ ]:
array = np.random.choice(50, 10, replace=False)
print('The array:', array)
n = 2

values = array[np.argpartition(-array,n)[:n]]
values = np.sort(values)[::1]
print(values)

The array: [44 41 13  6 38 37 33 48 31 17]
[44 48]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5])
vector3 = np.array([6, 7])

meshgrid = np.meshgrid(vector1, vector2, vector3)
#print(meshgrid)

result = np.column_stack([m.ravel() for m in meshgrid])

print(result)

[[1 4 6]
 [1 4 7]
 [2 4 6]
 [2 4 7]
 [3 4 6]
 [3 4 7]
 [1 5 6]
 [1 5 7]
 [2 5 6]
 [2 5 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
array = np.array([("name1", 10),
                  ("name2", 15)])

print('The regular array:\n', array)

record_array = np.core.records.fromarrays(array.T, 
                                          names='name, number',
                                          formats= 'U10, int')
print('\nThe record array:\n', record_array)
print('\n', record_array['number'])

The regular array:
 [['name1' '10']
 ['name2' '15']]

The record array:
 [('name1', 10) ('name2', 15)]

 [10 15]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
Z = np.random.randint(0, 10, 10)
print('The vector:', Z, '\n')

result = Z ** 3
print('The first method:', result, '\n')

result = np.power(Z, 3)
print('The second method:', result, '\n')

result = Z * Z * Z
print('The third method:', result)

The vector: [6 8 5 6 2 3 9 9 8 9] 

The first method: [216 512 125 216   8  27 729 729 512 729] 

The second method: [216 512 125 216   8  27 729 729 512 729] 

The third method: [216 512 125 216   8  27 729 729 512 729]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0, 4, (8, 3))
print('A:\n', A)
B = np.random.randint(0, 4, (2, 2))
print('B:\n', B)
result = (A[..., np.newaxis, np.newaxis] == B)
result = np.where(result.any((3,1)).all(1))[0]
print('The indices of rows:\n', result)

A:
 [[3 0 2]
 [3 2 1]
 [2 0 0]
 [2 3 1]
 [2 3 1]
 [2 2 3]
 [2 0 2]
 [2 0 2]]
B:
 [[1 1]
 [3 2]]
The indices of rows:
 [1 3 4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
array = np.random.randint(0, 3, (10, 3))
print('The initial array:\n', array)

array = array[~np.all(array[:, 1:] == array[:, :-1], axis=1)]
print('\nThe resulting array:\n', array)

The initial array:
 [[1 0 0]
 [2 0 2]
 [1 1 0]
 [1 0 1]
 [2 2 0]
 [2 1 2]
 [2 2 2]
 [0 0 0]
 [2 1 2]
 [1 0 2]]

The resulting array:
 [[1 0 0]
 [2 0 2]
 [1 1 0]
 [1 0 1]
 [2 2 0]
 [2 1 2]
 [2 1 2]
 [1 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
array = np.random.randint(0, 5, 5, dtype=np.uint8)
print('The initial array:\n', array)
array = np.unpackbits(array[:, np.newaxis], axis=1)
print('The resulting array:\n', array)

The initial array:
 [4 1 1 0 3]
The resulting array:
 [[0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
array = np.random.randint(0, 4, (7, 3))
print('The array:\n', array)
print(array.shape)
rows = np.unique(array, axis=0)
print('\nThe unique rows:\n', rows)
print(rows.shape)

The array:
 [[3 1 2]
 [3 1 0]
 [0 2 1]
 [1 2 0]
 [3 1 2]
 [1 1 0]
 [2 0 3]]
(7, 3)

The unique rows:
 [[0 2 1]
 [1 1 0]
 [1 2 0]
 [2 0 3]
 [3 1 0]
 [3 1 2]]
(6, 3)


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.randint(0, 5, 6)
B = np.random.randint(0, 5, 6)
print('A:', A)
print()
print('B:', B)
print()
inner = np.einsum('i,i->', A, B)
print('The inner function:', inner)
outer = np.einsum('i,j->ij', A, B)
print('The outer function:\n', outer)
sum = np.einsum('i->', A)
print('The sum function:', sum)
mul = np.einsum('i, i -> i', A, B)
print('The mul function:', mul)

A: [0 1 2 2 0 0]

B: [2 3 4 3 0 0]

The inner function: 17
The outer function:
 [[0 0 0 0 0 0]
 [2 3 4 3 0 0]
 [4 6 8 6 0 0]
 [4 6 8 6 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
The sum function: 5
The mul function: [0 3 8 6 0 0]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [574]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.array([[1.0, 0.0, 3.0, 8.0],
            [2.0, 0.0, 1.0, 1.0],
            [1.5, 2.5, 1.0, 0.0]])
n = 4

row_sums = np.sum(X, axis=1)

mask = (row_sums == n) & np.all(X.astype(int) == X, axis=1)

selected_rows = X[mask]

print(selected_rows)

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(5)
print('The 1D array:', X)
N = 100

sample_means = np.empty(N)

for i in range(N):
    resample = np.random.choice(X, size=len(X), replace=True)
    means[i] = np.mean(resample)

print()
print('The means of each sample:\n', np.sort(means))

interval = np.percentile(means, [2.5, 97.5])
print("\nThe 95% confidence intervals:", interval)

The 1D array: [ 1.97962261  0.60810547 -0.05471478  0.63841141  0.05104713]

The means of each sample:
 [-0.01241002  0.07784927  0.09900165  0.09900165  0.12621522  0.12621522
  0.22253569  0.2315657   0.24368808  0.24368808  0.25271808  0.25877927
  0.25877927  0.25877927  0.25877927  0.27993165  0.28599284  0.35509975
  0.38528213  0.39134332  0.39740451  0.47554142  0.48160261  0.48471675
  0.48471675  0.4876638   0.4876638   0.4876638   0.49372499  0.50586913
  0.51193032  0.51193032  0.52702151  0.52702151  0.5330827   0.5330827
  0.5330827   0.5330827   0.5330827   0.54817389  0.54817389  0.54817389
  0.54817389  0.6172808   0.62022785  0.62334199  0.62334199  0.62940317
  0.62940317  0.63843318  0.64449437  0.64449437  0.64449437  0.65958556
  0.66564675  0.66564675  0.67170794  0.67170794  0.67170794  0.67170794
  0.75590604  0.75590604  0.75590604  0.75902018  0.77099723  0.77099723
  0.77705842  0.77705842  0.77705842  0.78017256  0.78017256  0.78311961
  0.78311961  0.78311