# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [59]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [60]:
print('The NumpPy version:', np.__version__)
print('The NumPy configuration:')
np.show_config()

The NumpPy version: 1.24.3
The NumPy configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    i

#### 3. Create a null vector of size 10 (★☆☆)

In [61]:
nullVector = np.zeros(10)
print(nullVector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [62]:
print(nullVector.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [63]:
###pydoc numpy.add

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [64]:
nullVector = np.zeros(10)
nullVector[4] = 1
print(nullVector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [65]:
vector7 = np.arange(10,50)
print(vector7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [66]:
vector8 = vector7[::-1]
print(vector8)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [67]:
vector9 = np.arange(9).reshape(3,3)
print(vector9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [68]:
array10 = [1,2,0,0,4,0]
indices = np.nonzero(array10)
print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [69]:
identityMatrix = np.eye(3,3)
print(identityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [70]:
randomArray = np.random.rand(3,3,3)
print(randomArray)

[[[0.14264724 0.60593075 0.74038489]
  [0.44048883 0.17215196 0.6044371 ]
  [0.24693359 0.08125018 0.76423889]]

 [[0.02046955 0.72038307 0.97544238]
  [0.79649308 0.95657035 0.71738981]
  [0.32447939 0.82743991 0.77511034]]

 [[0.42924788 0.54904478 0.55162761]
  [0.76276113 0.88351064 0.74850787]
  [0.04605044 0.2369376  0.23403334]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [71]:
array13 = np.random.rand(10,10)
print('The array:\n', array13)
print('The minimum value:', array13.min())
print('The maximum value:', array13.max())

The array:
 [[0.00860121 0.0914032  0.95169847 0.72564901 0.20736704 0.88624137
  0.94727387 0.26016318 0.91856629 0.2513784 ]
 [0.92472243 0.64482679 0.49266784 0.80346215 0.12041191 0.31513391
  0.91436313 0.59126856 0.05402558 0.49959991]
 [0.3913427  0.72305425 0.70452179 0.74152911 0.63206021 0.38123252
  0.07539756 0.096503   0.25134161 0.20588794]
 [0.1760081  0.2017428  0.31167543 0.09294066 0.6036366  0.41954449
  0.37707859 0.81765376 0.04446124 0.18689778]
 [0.97441057 0.29200708 0.51476604 0.33527863 0.48026687 0.89448294
  0.08186073 0.02504005 0.26144559 0.57811807]
 [0.01812874 0.7953953  0.87071225 0.91768911 0.77362983 0.94625985
  0.84547613 0.70841853 0.46164596 0.79139596]
 [0.97024389 0.13238105 0.97800886 0.33356205 0.51449653 0.0334354
  0.53796761 0.7074645  0.90905606 0.84398096]
 [0.82952999 0.36704972 0.68416832 0.88496922 0.13594538 0.83842043
  0.06290567 0.32547802 0.35614493 0.69387979]
 [0.48557787 0.89713626 0.99396403 0.41848745 0.052596   0.49574439
 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [72]:
vector14 = np.random.rand(30)
print('The vector:\n', vector14)
print('The mean value:', vector14.mean())

The vector:
 [0.98916308 0.71084838 0.29280947 0.919276   0.45153273 0.72124958
 0.19514383 0.11905825 0.77275569 0.10642547 0.61657544 0.75101267
 0.14821502 0.63382604 0.6649091  0.13819544 0.16495421 0.20376405
 0.38160292 0.95940737 0.91780959 0.8019358  0.81135028 0.14500426
 0.39947639 0.02575992 0.8022822  0.87758026 0.7937512  0.95736718]
The mean value: 0.5491013947366616


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [73]:
array15 = np.ones((5,5))
array15[1:-1,1:-1] = 0
print(array15)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [74]:
initialArray = np.arange(9).reshape(3,3)
rows, columns = initialArray.shape
print('The initial array:\n', initialArray)

array16 = np.zeros((rows+2, columns+2))
array16[1:-1,1:-1] = initialArray
print('The resulting array:\n', array16)


The initial array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
The resulting array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 0.]
 [0. 3. 4. 5. 0.]
 [0. 6. 7. 8. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [75]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [76]:
array18 = np.diag(np.arange(1,5), k=-1)
print(array18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [77]:
array19 = np.zeros((8,8))
array19[1::2, ::2] = 1
array19[::2, 1::2] = 1
print(array19)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [78]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [79]:
array21 = np.tile(np.array([[0 , 1], [1, 0]]), (4, 4))
print(array21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [80]:
array22 = np.random.randint(-5, 5, (5, 5))
print('The initial array:\n', array22)
array22 = (array22 - np.mean(array22)) / np.std(array22)
print('\nThe resulting array:\n', array22)

The initial array:
 [[ 1  2  3 -4  4]
 [-3 -5  1 -4 -5]
 [ 2  0  1 -3 -1]
 [-5 -4  3  3 -2]
 [-1  2 -1 -2  3]]

The resulting array:
 [[ 0.55205245  0.89708523  1.24211801 -1.17311145  1.58715079]
 [-0.82807867 -1.51814423  0.55205245 -1.17311145 -1.51814423]
 [ 0.89708523  0.20701967  0.55205245 -0.82807867 -0.13801311]
 [-1.51814423 -1.17311145  1.24211801  1.24211801 -0.48304589]
 [-0.13801311  0.89708523 -0.13801311 -0.48304589  1.24211801]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [81]:
custom_dtype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [82]:
array24 = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(array24)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [83]:
array25 = np.arange(10)
array25[(3 < array25) & (array25 < 8)] *= -1
print(array25)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [84]:
print(sum(range(5), -1))
print(np.sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [85]:
Z = np.arange(5)
print('The array:\n', Z)
print('\nZ**Z\n', (Z**Z))
print('\n2 << Z >> 2\n', (2 << Z >> 2))
print('\nZ <- Z\n', (Z <- Z))
print('\n1j * Z\n', (1j*Z))
print('\nZ/1/1\n', (Z/1/1))
#print('\nZ<Z>Z\n', (Z<Z>Z))

The array:
 [0 1 2 3 4]

Z**Z
 [  1   1   4  27 256]

2 << Z >> 2
 [0 1 2 4 8]

Z <- Z
 [False False False False False]

1j * Z
 [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]

Z/1/1
 [0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [86]:
print('np.array(0) / np.array(0) =', np.array(0) / np.array(0))

print('\nnp.array(0) // np.array(0) =', np.array(0) // np.array(0))

print('\nnp.array([np.nan]).astype(int).astype(float) =', np.array([np.nan]).astype(int).astype(float))

np.array(0) / np.array(0) = nan

np.array(0) // np.array(0) = 0

np.array([np.nan]).astype(int).astype(float) = [-2.14748365e+09]


C:\Users\user\AppData\Local\Temp\ipykernel_6604\2212509283.py:1: RuntimeWarning: invalid value encountered in divide
  print('np.array(0) / np.array(0) =', np.array(0) / np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_6604\2212509283.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print('\nnp.array(0) // np.array(0) =', np.array(0) // np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_6604\2212509283.py:5: RuntimeWarning: invalid value encountered in cast
  print('\nnp.array([np.nan]).astype(int).astype(float) =', np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [87]:
array29 = np.arange(-3.2, 4, 0.75)
print('The initial array:\n', array29)
array29 = np.where(array29 > 0, np.ceil(array29), np.floor(array29))
print('\nThe resulting array:\n', array29)

The initial array:
 [-3.2  -2.45 -1.7  -0.95 -0.2   0.55  1.3   2.05  2.8   3.55]

The resulting array:
 [-4. -3. -2. -1. -1.  1.  2.  3.  3.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [88]:
array30_1 = np.random.randint(-5, 5, 10)
array30_2 = np.random.randint(-5, 5, 10)
print('The first array:\n', array30_1)
print('\nThe second array:\n', array30_2)
print('\nThe common values:\n', np.intersect1d(array30_1, array30_2))

The first array:
 [ 2 -5  2  4 -5  4  0  4 -2 -2]

The second array:
 [ 2 -2  3 -1 -5 -3 -3 -5 -1 -2]

The common values:
 [-5 -2  2]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [89]:
print(np.geterr(), '\n')
old_settings = np.seterr(all='ignore')  #seterr to known value
print(np.geterr(), '\n')
print(np.array(0) / np.array(0))
np.seterr(**old_settings)  # reset to default
print(np.geterr())
print(np.array(0) / np.array(0))

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'} 

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'} 

nan
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
nan


C:\Users\user\AppData\Local\Temp\ipykernel_6604\3434036659.py:7: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [90]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\user\AppData\Local\Temp\ipykernel_6604\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [91]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1)
tomorrow = today + np.timedelta64(1)

print('Yesterday:', yesterday)
print('Today:', today)
print('Tomorrow:', tomorrow)

Yesterday: 2023-10-17
Today: 2023-10-18
Tomorrow: 2023-10-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [92]:
july = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [93]:
A = np.array([1, 3, 5], dtype=float)
B = np.array([2, 4, 6], dtype=float)

print('A:', A)
print('\nB:', B)

np.add(A, B, out=B)
print('\nadd:', B)
np.negative(A, out=A)
print('\nnegative:', A)
np.divide(A, 2, out=A)
print('\ndivide:', A)
np.multiply(B, A, out=A)
print('\nmultiply:', A)

A: [1. 3. 5.]

B: [2. 4. 6.]

add: [ 3.  7. 11.]

negative: [-1. -3. -5.]

divide: [-0.5 -1.5 -2.5]

multiply: [ -1.5 -10.5 -27.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [94]:
array36 = np.random.rand(5)*10
print('The initial array:\n', array36)
print('\nThe first method:', array36 // 1)
print('\nThe second method:', np.ceil(array36))
print('\nThe third method:', np.floor(array36))
print('\nThe fourth method:', np.trunc(array36))

The initial array:
 [7.56597839 2.58877783 3.96878429 2.80245998 8.33808024]

The first method: [7. 2. 3. 2. 8.]

The second method: [8. 3. 4. 3. 9.]

The third method: [7. 2. 3. 2. 8.]

The fourth method: [7. 2. 3. 2. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [95]:
array37 = np.tile(np.array(np.arange(5)), (5, 1))
print(array37)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [96]:
def generator():
    for i in range(10):
        yield i

array38 = np.fromiter(generator(), dtype=int)

print(array38)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [97]:
#array39 = np.random.rand(10)
#array39 = np.arange(0, 1, 0.09)[1:11]
array39 = np.linspace(0, 1, 11, endpoint=False)[1:]
print(array39)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [98]:
array40 = np.random.random(10)*10
array40.sort()
print(array40)

[3.12853689 3.51490109 3.56683151 4.79486941 5.69298086 5.93821924
 6.20405195 6.44226407 7.55594829 8.55214524]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [99]:
array41 = np.random.randint(0, 10, 5)
print('The array:', array41)
print(np.add.reduce(array41))

The array: [8 9 1 0 2]
20


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [100]:
A = np.random.randint(0, 3, 3)
B = np.random.randint(0, 3, 3)
print('A:', A)
print('B:', B)
print(np.array_equal(A,B))

A: [0 0 1]
B: [0 0 1]
True


#### 43. Make an array immutable (read-only) (★★☆)

In [101]:
array43 = np.arange(5)
array43.flags.writeable = False
print('The initial array:', array43)
#array43[2] = 9

The initial array: [0 1 2 3 4]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [102]:
array44 = np.random.random((10, 2))

x, y = array44[:, 0], array44[:, 1]

radius = np.sqrt(x**2, y**2)
angle = np.arctan2(y, x)

print('The cartesian coordinates:\n', array44)
print('\nThe polar coordinates:')
print('The radius:\n', radius)
print('The angle:\n', angle)

The cartesian coordinates:
 [[9.33953446e-01 3.24662187e-01]
 [7.09710790e-01 9.66845797e-04]
 [2.60340921e-01 9.40357904e-01]
 [3.42575813e-01 2.49889701e-01]
 [2.09391517e-01 4.84716726e-01]
 [2.68674799e-01 8.58034824e-01]
 [9.58472442e-02 1.93011592e-01]
 [4.04380528e-01 2.33710234e-01]
 [9.85786709e-01 6.69957546e-01]
 [1.48761496e-01 7.76292655e-02]]

The polar coordinates:
The radius:
 [0.93395345 0.70971079 0.26034092 0.34257581 0.20939152 0.2686748
 0.09584724 0.40438053 0.98578671 0.1487615 ]
The angle:
 [0.33455421 0.00136231 1.3007082  0.63021463 1.16302221 1.26733936
 1.10988203 0.52404569 0.59691481 0.48096427]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [103]:
array45 = np.random.randint(0, 10, 10)
print('The initial array:\n', array45)
array45[array45.argmax()] = 0
print('\nThe resulting array:\n', array45)

The initial array:
 [3 4 0 8 5 2 0 8 3 7]

The resulting array:
 [3 4 0 0 5 2 0 8 3 7]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [104]:
x, y = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

array45 = np.ones((5*5), dtype=[('x', float), ('y', float)])

array45['x'] = x.flatten()
array45['y'] = y.flatten()

print("The structured array:")
print(array45)

The structured array:
[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [105]:
X = np.arange(1, 8)
Y = np.arange(5, 12)

print('X:', X)
print('\nY:', Y)

array47 = 1 / np.subtract.outer(X, Y)
print('\nThe Cauchy matrix:\n', array47)

X: [1 2 3 4 5 6 7]

Y: [ 5  6  7  8  9 10 11]

The Cauchy matrix:
 [[-0.25       -0.2        -0.16666667 -0.14285714 -0.125      -0.11111111
  -0.1       ]
 [-0.33333333 -0.25       -0.2        -0.16666667 -0.14285714 -0.125
  -0.11111111]
 [-0.5        -0.33333333 -0.25       -0.2        -0.16666667 -0.14285714
  -0.125     ]
 [-1.         -0.5        -0.33333333 -0.25       -0.2        -0.16666667
  -0.14285714]
 [        inf -1.         -0.5        -0.33333333 -0.25       -0.2
  -0.16666667]
 [ 1.                 inf -1.         -0.5        -0.33333333 -0.25
  -0.2       ]
 [ 0.5         1.                 inf -1.         -0.5        -0.33333333
  -0.25      ]]


C:\Users\user\AppData\Local\Temp\ipykernel_6604\2839036482.py:7: RuntimeWarning: divide by zero encountered in divide
  array47 = 1 / np.subtract.outer(X, Y)


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [106]:
itypes = [np.int8, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64]
ftypes = [np.float32, np.float64]

for type in itypes:
    info = np.iinfo(type)
    print(f'The minimum representable value for {type.__name__}:', info.min)
    print(f'The maximum representable value for {type.__name__}:', info.max)
    print()

for type in ftypes:
    info = np.finfo(type)
    print(f'The minimum representable value for {type.__name__}:', info.min)
    print(f'The maximum representable value for {type.__name__}:', info.max)
    print()

The minimum representable value for int8: -128
The maximum representable value for int8: 127

The minimum representable value for int32: -2147483648
The maximum representable value for int32: 2147483647

The minimum representable value for int64: -9223372036854775808
The maximum representable value for int64: 9223372036854775807

The minimum representable value for uint8: 0
The maximum representable value for uint8: 255

The minimum representable value for uint16: 0
The maximum representable value for uint16: 65535

The minimum representable value for uint32: 0
The maximum representable value for uint32: 4294967295

The minimum representable value for uint64: 0
The maximum representable value for uint64: 18446744073709551615

The minimum representable value for float32: -3.4028235e+38
The maximum representable value for float32: 3.4028235e+38

The minimum representable value for float64: -1.7976931348623157e+308
The maximum representable value for float64: 1.7976931348623157e+308



#### 49. How to print all the values of an array? (★★☆)

In [107]:
np.set_printoptions(threshold=float("inf"))
array49 = np.zeros((100,100))
print(array49)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [108]:
array50 = np.arange(1, 20, 3)
scalar = 12

print('The array:', array50)
print('\nThe scalar:', scalar)

element = np.abs(array50 - scalar).argmin()
print('\nThe closest value:', array50[element])

The array: [ 1  4  7 10 13 16 19]

The scalar: 12

The closest value: 13


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [109]:
dtype = np.dtype([
                ('position', [('x', int), ('y', int)]), 
                ('color', [('r', int), ('g', int), ('b', int)])
                ])

array51 = np.ones(3, dtype=dtype)
print(array51)

[((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [110]:
array52 = np.random.randint(1, 5, (4, 2))
print('The array:\n', array52)

distances = np.linalg.norm(array52[:, np.newaxis] - array52, axis=2)

print('\nThe point by point distances:\n', distances)

The array:
 [[4 2]
 [1 2]
 [2 4]
 [1 3]]

The point by point distances:
 [[0.         3.         2.82842712 3.16227766]
 [3.         0.         2.23606798 1.        ]
 [2.82842712 2.23606798 0.         1.41421356]
 [3.16227766 1.         1.41421356 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [111]:
array53 = np.random.random(10).astype(np.float32)*10
print(f'The {array53.dtype} array:\n', array53)
array53 = array53.astype(np.int32)
print(f'\nThe {array53.dtype} array:\n', array53)

The float32 array:
 [2.7474163  4.476657   3.0030491  7.5754976  8.937195   8.593738
 2.6899676  3.2642732  0.12179763 0.6449609 ]

The int32 array:
 [2 4 3 7 8 8 2 3 0 0]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [112]:
file = '54.txt'

array54 = np.genfromtxt(file, delimiter=",", dtype=np.int32, filling_values=0)
print(array54)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [113]:
array55 = np.arange(2, 6).reshape(2,2)

for index, value in np.ndenumerate(array55):
    print(f'Index: {index}\tValue: {value}')

Index: (0, 0)	Value: 2
Index: (0, 1)	Value: 3
Index: (1, 0)	Value: 4
Index: (1, 1)	Value: 5


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [135]:
X, Y = np.meshgrid(np.linspace(-1,1,3), np.linspace(-1,1,3))
print('X:\n', X)
print('\nY:\n', Y)

distances = np.sqrt(X*X+Y*Y)
gaussian_function = np.exp(-( (distances)**2 / ( 2.0) ) )
print('\nThe first way:\n',gaussian_function)

X:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]

Y:
 [[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]

The first way:
 [[0.36787944 0.60653066 0.36787944]
 [0.60653066 1.         0.60653066]
 [0.36787944 0.60653066 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [157]:
array57 = np.zeros((5, 5))
print('The initial array:\n', array57)
indices = np.random.choice(range(5*5), 10, replace=False)
print('\nThe indices:\n', indices)
values = np.random.randint(1, 10, 10)
print('\nThe values:\n', values)
np.put(array57, indices, values)
print('\nThe resulting array:\n', array57)

The initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

The indices:
 [12 22 15 17 19  7 21  4 11 24]

The values:
 [3 1 1 7 9 9 2 9 2 6]

The resulting array:
 [[0. 0. 0. 0. 9.]
 [0. 0. 9. 0. 0.]
 [0. 2. 3. 0. 0.]
 [1. 0. 7. 0. 9.]
 [0. 2. 1. 0. 6.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [170]:
array58 = np.random.randint(0, 10, (3, 3))
print('The initial array:\n', array58)
meanValues = np.mean(array58, axis=1, keepdims=True)
print('\nThe mean value:\n', meanValues)
array58 = array58 - meanValues
print('\nThe resulting array:\n', array58)

The initial array:
 [[3 2 9]
 [8 5 2]
 [1 1 7]]

The mean value:
 [[4.66666667]
 [5.        ]
 [3.        ]]

The resulting array:
 [[-1.66666667 -2.66666667  4.33333333]
 [ 3.          0.         -3.        ]
 [-2.         -2.          4.        ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [186]:
array59 = np.random.randint(1, 10, (3, 3))
print('The initial array:\n', array59)
array59 = array59[array59[:, 0].argsort()]
print('\nThe resulting array:\n', array59)

The initial array:
 [[4 2 2]
 [1 4 6]
 [9 3 5]]

The resulting array:
 [[1 4 6]
 [4 2 2]
 [9 3 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [204]:
array60 = np.random.randint(0,3,(3,3))
print('The array:\n', array60)
nullColumns = (~array60.any(axis=0)).any()
print('\nThe array has null columns:', nullColumns)

The array:
 [[2 0 2]
 [1 1 2]
 [2 0 2]]

The array has null columns: False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [218]:
array61 = np.random.randint(0, 10, 5)
print('The array:', array61)
value = 3.7
print('The given value:', value)
print('The nearest value:', array61[(np.abs(array61 - value)).argmin()])

The array: [3 1 6 3 3]
The given value: 3.7
The nearest value: 3


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [234]:
array62_1 = np.random.randint(0, 10, (1, 3))
array62_2 = np.random.randint(0, 10, (3, 1))
print('The first array:\n', array62_1)
print('\nThe second array:\n', array62_2)

iter1 = np.nditer(array62_1)
iter2 = np.nditer(array62_2)

sum = 0

for i in iter1:
    for j in iter2:
        sum += i + j

print('\nThe sum:', sum)

The first array:
 [[1 6 6]]

The second array:
 [[4]
 [3]
 [1]]

The sum: 11


#### 63. Create an array class that has a name attribute (★★☆)

In [245]:
class namedArray(np.ndarray):
    def __new__(cls, arr, name='Unnamed'):
        obj = np.asarray(arr).view(cls)
        obj.name = name
        return obj

array63 = namedArray(np.arange(5), name='array name')
print('The array name:', array63.name, '\n', array63)

The array name: array name 
 [0 1 2 3 4]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [278]:
vector64 = np.random.randint(0, 10, 10)
print('The initial vector:', vector64)

indices = np.random.choice(len(vector64), 5)
print('The indices:', indices)

unique, counts = np.unique(indices, return_counts=1)

vector64[unique] += counts

print("\nThe resulting vector:", vector64)

The initial vector: [8 8 7 4 3 1 1 6 6 4]
The indices: [8 4 3 7 4]

The resulting vector: [8 8 7 5 5 1 1 7 7 4]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)